#pragma once

#include "llama.h"
#include "common.h"

struct common_speculative;

// comma separated list of all types
std::string common_speculative_type_name_str();

// convert string to type
enum common_speculative_type common_speculative_type_from_name(const std::string & name);

// convert type to string
std::string common_speculative_type_to_str(enum common_speculative_type type);

common_speculative * common_speculative_init(
        common_params_speculative & params,
        llama_context             * ctx_tgt);

void common_speculative_free(common_speculative * spec);

// optionally call once at the beginning of a new generation
void common_speculative_begin(common_speculative * spec, const llama_tokens & prompt);

// sample up to n_draft tokens and add them to the batch using the draft model
llama_tokens common_speculative_draft(
                     common_speculative * spec,
        const common_params_speculative & params,
                     const llama_tokens & prompt,
                            llama_token   id_last);

// informs the speculative decoder that n_accepted tokens were accepted by the target model
void common_speculative_accept(common_speculative * spec, uint16_t n_accepted);

// Returns a 0-based draft position where acceptance should be forced to stop.
// Returns -1 when the hook is disabled or outside the current draft size.
int common_speculative_force_reject_at(const common_speculative * spec, size_t n_draft);

// print statistics about the speculative decoding
void common_speculative_print_stats(const common_speculative * spec);

// Total raw draft tokens generated by all impls (pre-truncation).
// Useful when you want a real "drafts produced vs drafts accepted"
// ratio — the slot's n_draft_total counter is post-truncation, so
// dividing draft_n_accepted by draft_n produces a misleading
// near-100% rate even when many drafts were rejected upstream.
size_t common_speculative_n_gen_tokens(const common_speculative * spec);

// Total draft tokens accepted by the target across all impls.
size_t common_speculative_n_acc_tokens(const common_speculative * spec);

struct common_speculative_deleter {
    void operator()(common_speculative * s) { common_speculative_free(s); }
};

typedef std::unique_ptr<common_speculative, common_speculative_deleter> common_speculative_ptr;
